source_list:
  - SB
  - OL
  - CP
  - ADDR

target_list:
  - REGIS_DIM
  - CHILD_DIM

SB:
  mysql_conf:
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC) as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data
      filename: receipts_delta_GBR_14_10_2017.csv
CP:
  s3_conf:
    s3_bucket: mohsinali
    cust_dir: data
    filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: cust
    collection: address

s3_conf:
  s3_bucket: mohsinali
  staging_dir: staging

REGIS_DIM:
  tableName: DATAMART.REGIS_DIM
  source_data: CP
  loadingQuery: >
    SELECT
      MONOTONICALLY_INCREASING_ID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, run_dt
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, run_dt
      FROM
        CP
      WHERE
        run_dt = '2021-09-06'
      ) CP

CHILD_DIM:
  tableName: DATAMART.CHILD_DIM
  source_data: CP
  loadingQuery: >
      SELECT
          MONOTONICALLY_INCREASING_ID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB,
          CHILD_GENDER, run_dt
      FROM
           (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, run_dt
      FROM
          CP
      WHERE
          run_dt = '2021-09-06' AND CHILD_ID IS NOT NULL
      ) CP

RTL_TXN_FCT:
  source_data:
    - SB
    - OL
  target_src_table: REGIS_DIM
  tableName: DATAMART.RTL_TXN_FCT
  loadingQuery: >
      SELECT
          MONOTONICALLY_INCREASING_ID() AS RTL_TXN_KEY, CAST(TXN.APP_TRANSACTION_ID AS STRING)AS TXN_ID, SIZE(split(REC.PRODUCTS, ',')) AS TXN_ITEM_QTY,
          TRANSACTION_POINT_VALUE AS TXN_LOY_VAL_STD_CCY, 0 AS TXN_GROSS_MNY_STD_CCY, TRANSACTION_RETAIL_VALUE AS TXN_GROSS_MNY_LCL_CCY,
          -1 AS MNY_LCL_CCY_TYPE_KEY, TRANSACTION_EXTERNAL_REFERENCE AS RTL_TXN_TYPE_KEY, ACTIVITY_TIMESTAMP AS TXN_TS,
          CAST(ACTIVITY_TIMESTAMP AS DATE) AS TXN_DT_KEY, HOUR(ACTIVITY_TIMESTAMP) AS TXN_TM_HOUR, MINUTE(ACTIVITY_TIMESTAMP) AS TXN_TM_MINUTE,
          SECOND(ACTIVITY_TIMESTAMP) AS TXN_TM_SECOND, '-1' AS CHNL_KEY, REG.CNSM_ID AS CNSM_ID,
          "@NULL@" AS RTL_TXN_EXT_DEC_1, "@NULL@" AS RTL_TXN_EXT_DEC_2, REC.BASE_POINT_VALUE AS
          RTL_TXN_EXT_DEC_3, MOBILE_UID AS RTL_TXN_EXT_CHAR_1, MOBILE_OS AS RTL_TXN_EXT_CHAR_2, PRODUCTS AS RTL_TXN_EXT_CHAR_3,
          RECEIPT_STATUS AS RTL_TXN_EXT_CHAR_4, CAST(MSG_CODE AS BIGINT) AS RTL_TXN_EXT_CHAR_5, TXN.INS_DT AS RUN_DT
      FROM
          SB TXN LEFT OUTER JOIN OL REC
            ON (TXN.APP_TRANSACTION_ID = REC.SBLP_TRANSACTION_ID )
          LEFT OUTER JOIN REGIS_DIM REG
            ON REC.LOYALTY_ID = REG.CNSM_ID
      WHERE
          TXN.RUN_DT = '2021-09-06'
            AND (REC.RUN_DT = '2021-09-06' OR REC.RUN_DT is NULL)

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.sales
  query: SELECT sellerid, pricepaid from PUBLIC.sales

spark_sql_demo:
  agg_demo: >
    select
        AccountNumber,
        UniqueTransactionDescriptions,
        sort_array(UniqueTransactionDescriptions, false) as OrderedUniqueTransactionDescriptions,
        size(UniqueTransactionDescriptions) as CountOfUniqueTransactionTypes,
        array_contains(UniqueTransactionDescriptions, 'Movies') as WentToMovies
    from
        agg_finances
  case_when_demo: >
    select
        company,
        employee.firstName as firstName,
        case
            when company = 'FamilyCo' then 'Premium'
            when company = 'OldCo' then 'Legacy'
            else 'Standard'
        end as Tier
    from
        employees